config/routes.rb
Rails.application.routes.draw do
  resources :assign_tasks
  resources :tasks
  resources :projects
  devise_for :users, controllers: {
                        :registrations => 'user/registrations',
                    }
  resources :task_assig
   resources :task_activities, only: [:index] do
    collection do
      get :change_status
    end
   end
  
	root to: "dashbord#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assign_task.rb
class AssignTask < ApplicationRecord
	  belongs_to :task
	  belongs_to :assignee, :class_name => "User", :foreign_key => 'assignee_id'
	  belongs_to :assigner, :class_name => "User", :foreign_key => 'assigner_id'
	  after_save :change_task_status
	  enum status: {New: 1, Inprogress: 2, Done: 3}
	  scope :by_user, -> (user_id){ where(assignee_id: user_id) }

	    

	  def change_task_status
	  	self.task.update_columns(is_assigned: true)
	  end
end

app/controllers/assign_tasks_controller.rb
class AssignTasksController < ApplicationController
      load_and_authorize_resource
  before_action :set_assign_task, only: [:show, :edit, :update, :destroy]

  # GET /assign_tasks
  # GET /assign_tasks.json
  def index
    @assign_tasks = AssignTask.all
  end

  # GET /assign_tasks/1
  # GET /assign_tasks/1.json
  def show
  end

  # GET /assign_tasks/new
  def new
    @assign_task = AssignTask.new
  end

  # GET /assign_tasks/1/edit
  def edit
  end

  # POST /assign_tasks
  # POST /assign_tasks.json
  def create
    @assign_task = AssignTask.new(assign_task_params)
    @assign_task.assigner_id = current_user.id
    respond_to do |format|
      if @assign_task.save
        format.html { redirect_to @assign_task, notice: 'Assign task was successfully created.' }
        format.json { render :show, status: :created, location: @assign_task }
      else
        format.html { render :new }
        format.json { render json: @assign_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assign_tasks/1
  # PATCH/PUT /assign_tasks/1.json
  def update
    respond_to do |format|
      if @assign_task.update(assign_task_params)
        format.html { redirect_to @assign_task, notice: 'Assign task was successfully updated.' }
        format.json { render :show, status: :ok, location: @assign_task }
      else
        format.html { render :edit }
        format.json { render json: @assign_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assign_tasks/1
  # DELETE /assign_tasks/1.json
  def destroy
    @assign_task.destroy
    respond_to do |format|
      format.html { redirect_to assign_tasks_url, notice: 'Assign task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assign_task
      @assign_task = AssignTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assign_task_params
      params.require(:assign_task).permit(:task_id, :assignee_id)
    end
end

app/helpers/assign_tasks_helper.rb
module AssignTasksHelper
end

app/views/assign_tasks/_form.html.erb
<%= form_with(model: assign_task, local: true) do |f| %>
  <% if assign_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assign_task.errors.count, "error") %> prohibited this assign_task from being saved:</h2>

      <ul>
      <% assign_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %>
    <%= f.select :task_id, options_for_select(get_tasks), {}, {}%>
  </div>

  <div class="field">
    <%= f.label :assignee_id %>
    <%= f.select :assignee_id, options_for_select(get_users), {}, {}%>
  </div>
  <div class="actions">
    <%= f.submit "Assign this task" %>
  </div>
<% end %>

app/views/assign_tasks/edit.html.erb
<h1>Editing Assign Task</h1>

<%= render 'form', assign_task: @assign_task %>

<%= link_to 'Show', @assign_task %> |
<%= link_to 'Back', assign_tasks_path %>

app/views/assign_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assign Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Assignee</th>
      <th>Assigner</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assign_tasks.each do |assign_task| %>
      <tr>
        <% if assign_task.task != nil %>
        <td><%= assign_task.task.t_name %></td>
        <td><%= assign_task.assignee.email %></td>
        <td><%#= assign_task.assigner.email %></td>
        <td><%= assign_task.status %></td>
        <td><%= link_to 'Show', assign_task %></td>
        <td><%= link_to 'Edit', edit_assign_task_path(assign_task) %></td>
        <td><%= link_to 'Destroy', assign_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assign Task', new_assign_task_path %>

app/views/assign_tasks/new.html.erb
<h1>New Assign Task</h1>

<%= render 'form', assign_task: @assign_task %>

<%= link_to 'Back', assign_tasks_path %>

app/views/assign_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @assign_task.task.t_name %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @assign_task.assignee.email %>
</p>

<p>
  <strong>Assigner:</strong>
  <%= @assign_task.assigner.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @assign_task.status %>
</p>

<%= link_to 'Edit', edit_assign_task_path(@assign_task) %> |
<%= link_to 'Back', assign_tasks_path %>