config/routes.rb
Rails.application.routes.draw do
  resources :assign_tasks
  resources :tasks
  resources :projects
  devise_for :users, controllers: {
                        :registrations => 'user/registrations',
                    }
  resources :task_assig
   resources :task_activities, only: [:index] do
    collection do
      get :change_status
    end
   end
  
	root to: "dashbord#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Task manager" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Task manager", root_path, class: "navbar-brand"  %>
        <!-- <a class="navbar-brand" href="#">Taskmanager</a> -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><a><%= current_user.present? ? current_user.email : "Hi Guest" %></a  ></li>
            <% if current_user %>
               <li><%= link_to "logout", destroy_user_session_path, method: :delete  %></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <!-- <h3>Sidebar</h3> -->
            <ul class="nav nav-list">
              <li class="nav-header">
                <strong>Navigations</strong>
              </li>
              <% if current_user %>
               <!-- <li><%= link_to "logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete  %></li> -->
               <li><%= link_to "Edit My Profile", edit_user_registration_path(current_user.id), class: "btn btn-xs btn-warning"  %></li>
               <li><%= link_to "Projects", projects_path, class: "btn btn-xs btn-primary"  %></li>
               <li><%= link_to "tasks", tasks_path, class: "btn btn-xs btn-primary"  %></li>
               <li><%= link_to "Assign Task", assign_tasks_path, class: "btn btn-xs btn-primary"  %></li>
               <li><%= link_to "Task Activities", task_activities_path, class: "btn btn-xs btn-primary"  %></li>
              <% else %>
                <!-- <li><%= link_to "Login", new_user_session_path, class: "btn btn-xs btn-success" %></li>
                <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-xs btn-primary" %></li> -->
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>